// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/emersion/go-imap/v2"
	"github.com/emersion/go-imap/v2/imapclient"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConn creates a new instance of MockConn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConn(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConn {
	mock := &MockConn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConn is an autogenerated mock type for the Conn type
type MockConn struct {
	mock.Mock
}

type MockConn_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConn) EXPECT() *MockConn_Expecter {
	return &MockConn_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockConn
func (_mock *MockConn) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConn_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockConn_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockConn_Expecter) Close() *MockConn_Close_Call {
	return &MockConn_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockConn_Close_Call) Run(run func()) *MockConn_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConn_Close_Call) Return(err error) *MockConn_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConn_Close_Call) RunAndReturn(run func() error) *MockConn_Close_Call {
	_c.Call.Return(run)
	return _c
}

// FetchMessages provides a mock function for the type MockConn
func (_mock *MockConn) FetchMessages(numSet imap.NumSet, options *imap.FetchOptions) ([]*imapclient.FetchMessageBuffer, error) {
	ret := _mock.Called(numSet, options)

	if len(ret) == 0 {
		panic("no return value specified for FetchMessages")
	}

	var r0 []*imapclient.FetchMessageBuffer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(imap.NumSet, *imap.FetchOptions) ([]*imapclient.FetchMessageBuffer, error)); ok {
		return returnFunc(numSet, options)
	}
	if returnFunc, ok := ret.Get(0).(func(imap.NumSet, *imap.FetchOptions) []*imapclient.FetchMessageBuffer); ok {
		r0 = returnFunc(numSet, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*imapclient.FetchMessageBuffer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(imap.NumSet, *imap.FetchOptions) error); ok {
		r1 = returnFunc(numSet, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConn_FetchMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchMessages'
type MockConn_FetchMessages_Call struct {
	*mock.Call
}

// FetchMessages is a helper method to define mock.On call
//   - numSet imap.NumSet
//   - options *imap.FetchOptions
func (_e *MockConn_Expecter) FetchMessages(numSet any, options any) *MockConn_FetchMessages_Call {
	return &MockConn_FetchMessages_Call{Call: _e.mock.On("FetchMessages", numSet, options)}
}

func (_c *MockConn_FetchMessages_Call) Run(run func(numSet imap.NumSet, options *imap.FetchOptions)) *MockConn_FetchMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 imap.NumSet
		if args[0] != nil {
			arg0 = args[0].(imap.NumSet)
		}
		var arg1 *imap.FetchOptions
		if args[1] != nil {
			arg1 = args[1].(*imap.FetchOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConn_FetchMessages_Call) Return(fetchMessageBuffers []*imapclient.FetchMessageBuffer, err error) *MockConn_FetchMessages_Call {
	_c.Call.Return(fetchMessageBuffers, err)
	return _c
}

func (_c *MockConn_FetchMessages_Call) RunAndReturn(run func(numSet imap.NumSet, options *imap.FetchOptions) ([]*imapclient.FetchMessageBuffer, error)) *MockConn_FetchMessages_Call {
	_c.Call.Return(run)
	return _c
}

// ListMailboxes provides a mock function for the type MockConn
func (_mock *MockConn) ListMailboxes() ([]string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListMailboxes")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConn_ListMailboxes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMailboxes'
type MockConn_ListMailboxes_Call struct {
	*mock.Call
}

// ListMailboxes is a helper method to define mock.On call
func (_e *MockConn_Expecter) ListMailboxes() *MockConn_ListMailboxes_Call {
	return &MockConn_ListMailboxes_Call{Call: _e.mock.On("ListMailboxes")}
}

func (_c *MockConn_ListMailboxes_Call) Run(run func()) *MockConn_ListMailboxes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConn_ListMailboxes_Call) Return(strings []string, err error) *MockConn_ListMailboxes_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockConn_ListMailboxes_Call) RunAndReturn(run func() ([]string, error)) *MockConn_ListMailboxes_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type MockConn
func (_mock *MockConn) Logout() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConn_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockConn_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
func (_e *MockConn_Expecter) Logout() *MockConn_Logout_Call {
	return &MockConn_Logout_Call{Call: _e.mock.On("Logout")}
}

func (_c *MockConn_Logout_Call) Run(run func()) *MockConn_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConn_Logout_Call) Return(err error) *MockConn_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConn_Logout_Call) RunAndReturn(run func() error) *MockConn_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Select provides a mock function for the type MockConn
func (_mock *MockConn) Select(mailbox string) error {
	ret := _mock.Called(mailbox)

	if len(ret) == 0 {
		panic("no return value specified for Select")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(mailbox)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConn_Select_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Select'
type MockConn_Select_Call struct {
	*mock.Call
}

// Select is a helper method to define mock.On call
//   - mailbox string
func (_e *MockConn_Expecter) Select(mailbox any) *MockConn_Select_Call {
	return &MockConn_Select_Call{Call: _e.mock.On("Select", mailbox)}
}

func (_c *MockConn_Select_Call) Run(run func(mailbox string)) *MockConn_Select_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConn_Select_Call) Return(err error) *MockConn_Select_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConn_Select_Call) RunAndReturn(run func(mailbox string) error) *MockConn_Select_Call {
	_c.Call.Return(run)
	return _c
}

// UIDSearch provides a mock function for the type MockConn
func (_mock *MockConn) UIDSearch(criteria *imap.SearchCriteria) ([]imap.UID, error) {
	ret := _mock.Called(criteria)

	if len(ret) == 0 {
		panic("no return value specified for UIDSearch")
	}

	var r0 []imap.UID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*imap.SearchCriteria) ([]imap.UID, error)); ok {
		return returnFunc(criteria)
	}
	if returnFunc, ok := ret.Get(0).(func(*imap.SearchCriteria) []imap.UID); ok {
		r0 = returnFunc(criteria)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]imap.UID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*imap.SearchCriteria) error); ok {
		r1 = returnFunc(criteria)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConn_UIDSearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UIDSearch'
type MockConn_UIDSearch_Call struct {
	*mock.Call
}

// UIDSearch is a helper method to define mock.On call
//   - criteria *imap.SearchCriteria
func (_e *MockConn_Expecter) UIDSearch(criteria any) *MockConn_UIDSearch_Call {
	return &MockConn_UIDSearch_Call{Call: _e.mock.On("UIDSearch", criteria)}
}

func (_c *MockConn_UIDSearch_Call) Run(run func(criteria *imap.SearchCriteria)) *MockConn_UIDSearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *imap.SearchCriteria
		if args[0] != nil {
			arg0 = args[0].(*imap.SearchCriteria)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConn_UIDSearch_Call) Return(uIDs []imap.UID, err error) *MockConn_UIDSearch_Call {
	_c.Call.Return(uIDs, err)
	return _c
}

func (_c *MockConn_UIDSearch_Call) RunAndReturn(run func(criteria *imap.SearchCriteria) ([]imap.UID, error)) *MockConn_UIDSearch_Call {
	_c.Call.Return(run)
	return _c
}
